# Generated by Django 3.2.16 on 2022-12-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_over", models.BooleanField(default=0)),
            ],
            options={
                "verbose_name": "битва",
                "verbose_name_plural": "битвы",
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "вызов",
                "verbose_name_plural": "вызовы",
            },
        ),
        migrations.CreateModel(
            name="PlayerAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_right", models.BooleanField(null=True)),
            ],
            options={
                "verbose_name": "вопрос в раунде",
                "verbose_name_plural": "вопросы в раунде",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_over", models.BooleanField(default=0)),
                (
                    "battle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="duels.battle",
                    ),
                ),
            ],
            options={
                "verbose_name": "раунд",
                "verbose_name_plural": "раунды",
            },
        ),
    ]
