# Generated by Django 3.2.16 on 2022-12-29 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questions", "0002_auto_20221229_1723"),
        ("duels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="player_1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battle_player1",
                to="users.customuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="battle",
            name="player_2",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battle_player2",
                to="users.customuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="challenge",
            name="player_recieved_id",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_recieved",
                to="users.customuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="challenge",
            name="player_sent_id",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_sent",
                to="users.customuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playeranswer",
            name="player_id",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battle_player",
                to="users.customuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playeranswer",
            name="question_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.question",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playeranswer",
            name="round_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="duels.round",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="round",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.category",
            ),
            preserve_default=False,
        ),
    ]
