# Generated by Django 3.2.16 on 2022-12-22 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
        ('duels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.category'),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='round_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duels.round'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='player_recieved_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_recieved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='player_sent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
