# Generated by Django 3.2.16 on 2023-01-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duels", "0007_playeranswer_start_answering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playeranswer",
            name="player_answer",
            field=models.CharField(
                max_length=150, verbose_name="ответ игрока"
            ),
        ),
    ]
