# Generated by Django 3.2.16 on 2023-01-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0008_alter_playeranswer_player_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='player_1_scores',
            field=models.IntegerField(default=0, verbose_name='очки первого игрока'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_2_scores',
            field=models.IntegerField(default=0, verbose_name='очки второго игрока'),
        ),
    ]
