# Generated by Django 5.2.7 on 2025-11-07 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "duels",
            "0011_battle_player_1_scores_battle_player_2_scores_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
