# Generated by Django 3.2.16 on 2022-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default="..\\static_dev\\homepage\\img\\me.png",
                upload_to="uploads/%Y/%m",
            ),
        ),
    ]
