# Generated by Django 3.2.16 on 2022-12-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20221222_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="login",
            field=models.CharField(
                help_text="Максимальная длина 13 символов",
                max_length=13,
                unique=True,
                verbose_name="имя пользователя",
            ),
        ),
    ]
