# Generated by Django 3.2.16 on 2022-12-21 16:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221220_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='..\\static_dev\\homepage\\img\\me.png', storage=django.core.files.storage.FileSystemStorage(location='media/media/'), upload_to='uploads/%Y/%m'),
        ),
    ]
