# Generated by Django 3.2.16 on 2022-12-21 18:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default="",
                storage=django.core.files.storage.FileSystemStorage(
                    location="media/"
                ),
                upload_to="",
            ),
        ),
    ]
