# Generated by Django 3.2.16 on 2022-12-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='null', upload_to='uploads/%Y/%m', verbose_name='аватар'),
        ),
    ]
