# Generated by Django 3.2.16 on 2022-12-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created",
        ),
        migrations.RemoveField(
            model_name="category",
            name="modified",
        ),
    ]
