# Generated by Django 3.2.16 on 2022-12-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("duels", "0005_alter_round_category"),
        ("users", "0004_alter_customuser_best_category"),
        ("questions", "0004_auto_20221222_0235"),
        ("arena", "0002_auto_20221221_1901"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
