# Generated by Django 3.2.16 on 2022-12-22 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created",
        ),
        migrations.RemoveField(
            model_name="category",
            name="modified",
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="right_answer",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
