# Generated by Django 3.2.16 on 2022-12-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20221221_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
