# Generated by Django 3.2.16 on 2022-12-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_approved',
            field=models.BooleanField(default=0),
        ),
    ]
