# Generated by Django 3.2.16 on 2022-12-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created", models.DateTimeField(editable=False)),
                ("modified", models.DateTimeField()),
            ],
            options={
                "verbose_name": "категория вопроса",
                "verbose_name_plural": "категории вопросов",
            },
        ),
    ]
